create table if not exists books (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  description text,
  vote_count integer not null default 0,
  author text,
  published_year integer,
  cover_image_url text,
  open_library_id text,
  page_count integer
);
